import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";
import Header  from "@/components/header";


const inter= Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Career Mentor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    /* wrapping the entire layout with clerk provider for authentication */

    <ClerkProvider>

    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
        >
        {/* light mode dark mode wrapper aka ThemeProvider, wraps the children */}
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            >

        {/* header */}
        <Header/>

        <main className="min-h-screen">
        {children}
        </main>

        {/* footer */}
        <footer className="bg-muted/50 py-12">
          <div className="container mx-auto px-4 text-center text-gray-200">
            <p>Footer content</p>
          </div>
        </footer>

        </ThemeProvider>
      </body>
    </html>

    </ClerkProvider>
  );
}
